### ISSUE TITLE
The image can not docker run

### ISSUE THREAD

**Issue by qibobo** [SUSE/fissile#309]
I made a role manifest to build the docker image successfully, but when I tried to use docker run $imageName:tag, I got the error as below:
/usr/local/rvm/gems/ruby-2.3.1/gems/bosh-template-1.3262.24.0/lib/bosh/template/evaluation_context.rb:93:in `p': Can't find property '["fissile.monit.port"]' (Bosh::Template::UnknownProperty)
	from /opt/scf/monitrc.erb:9:in `get_binding'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/erb.rb:864:in `result'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/configgin-0.12.0.pre/lib/generate.rb:30:in `generate'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/configgin-0.12.0.pre/bin/configgin:34:in `block (2 levels) in <top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/configgin-0.12.0.pre/bin/configgin:23:in `each'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/configgin-0.12.0.pre/bin/configgin:23:in `block in <top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/configgin-0.12.0.pre/bin/configgin:20:in `each'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/configgin-0.12.0.pre/bin/configgin:20:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/configgin:23:in `load'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/configgin:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by aarondl** [comment]
Currently configgin has ended up with a hard dependency on Kubernetes which we need to resolve. We have an internal issue for this.

**Comment by aarondl** [comment]
Wait a sec, this looks like a different problem. I'd have to see the opinions.yaml that you used as well as the role manifest to understand what's going on here.

**Comment by qibobo** [comment]
@aarondl After adding the job 
 `- name: global-properties`
`    release_name: scf-helper`
to each role, the error fixed. I encountered the same error when I tried with fissile demo: 
[https://github.com/SUSE/fissile/blob/master/docs/configuration.md](url)
Is the job "global-properties" necessary for every role? If yes, can you update the fissile document? Or if no, how to config the role manifest without it?
Below is a sample of my role:
- name: postgres_autoscaler
  jobs:
  - name: global-properties # needs to be first so images use it for processing monit templates
    release_name: scf-helper
  - name: postgres
    release_name: ibm-cf
  - name: consul_agent
    release_name: ibm-cf
  processes:
  - name: consul_agent
  - name: postgres
  tags: ['clustered']
  run:
    scaling:
      min: 1
      max: 1
      ha: 2
    capabilities: []
    persistent-volumes: []
    shared-volumes: []
    memory: 256
    virtual-cpus: 2
    exposed-ports:
    - name: postgres
      protocol: TCP
      external: 5432
      internal: 5432
      public: false
